### ISSUE TITLE
DOC: Video content status.

### ISSUE THREAD

**Issue by AnneTheAgile** [pyvideo/pyvideo-data#12]
I am sorry pyvideo is leaving. Thank you for all your hard work. I loved it with a passion because all our user conferences' videos went up so quickly. 

Where is all the content going? If I'd like to watch PyGotham from 2015 where should I look after the site dies?
thank you!
Anne

**Comment by codersquid** [comment]
Hi @AnneTheAgile the PyGotham 2015 videos are on youtube and shouldn't vanish. The metadata that pyvideo.org has should be in this repo in the data directory. I filed #20 because I just noticed it was missing.

Once we have more news about the progress on pyvideo-data, we'll make a new blog post. Please keep in touch.

**Comment by AnneTheAgile** [comment]
ty @codersquid !

**Comment by codersquid** [comment]
Hi @AnneTheAgile 

I'll close this out, but comment/reopen if I did not answer your question.

Here is the latest post about the project: http://bluesock.org/~willkg/blog/pyvideo/status_20160316.html
